### ISSUE TITLE
Only has one file with many groups

### ISSUE THREAD

**Issue by arcchang1236** [fab-jul/hdf5_dataloader#1]
Hello,
If I only have one h5py file with many groups
How can I use this package?

**Comment by fab-jul** [comment]
The package is made for many HDF5 files ("shards") because that is what's most efficient on our clusters. If you only have one, I would assume you can do cache the file somewhere, `f = h5py.File(p, 'r')`, and then write a simple subclass of `Dataset` that just indexes into that file.
